language: cpp
dist: focal
matrix:
  include:
    compiler: g++
    os: linux
    sudo: required

before_script: |
    sudo apt-get update
    sudo apt-get install build-essential scons git python3-ruamel.yaml python3-yaml g++ gfortran python libboost-dev cython python-dev python-numpy python-numpy-dev python-setuptools python3 python3-dev python3-setuptools python3-numpy cython3
    sudo update-alternatives --install /usr/bin/python python /usr/bin/python3 1
    sudo apt-get install libgtkmm-3.0-dev
    sudo apt-get install libplplot-dev plplot-driver-cairo
    git clone https://github.com/Cantera/cantera.git -b 2.5 --depth=1

branches:
  only:
  - master
script: |
    cd cantera
    scons build system_sundials=n
    sudo scons install
    cd ..
    cd GUI/Ubuntu
    ./build.sh -c
    ./build.sh --no-interaction
