language: cpp
dist: focal
matrix:
  include:
    compiler: g++
    os: linux
    sudo: required

before_script: |
    sudo apt-get install scons git python3-ruamel.yaml python3-yaml
    sudo apt-get install build-essential libgtkmm-3.0-dev g++ gfortran python libboost-dev cython python-dev python-numpy python-numpy-dev python-setuptools python3 python3-dev python3-setuptools python3-numpy cython3 python3-matplotlib
    sudo update-alternatives --install /usr/bin/python python /usr/bin/python3 1
    git clone https://github.com/Cantera/cantera.git

branches:
  only:
  - master
script: |
    cd cantera
    scons build system_sundials=n
    sudo scons install
    cd ..
    cd GUI/Ubuntu
    ./build.sh -c
    ./build.sh --no-interaction
