language: cpp
dist: xenial
matrix:
  include:
  - #dist: xenial
    compiler: g++
    os: linux
    sudo: required
  - dist: bionic
    compiler: g++
    os: linux
    sudo: required

before_script: |
    if [[ "$TRAVIS_DIST" == "xenial" ]]; then
        sudo apt-get install git python3-pip
        git clone https://github.com/SCons/scons.git
    else
        sudo apt-get install scons git python3-ruamel.yaml python3-yaml
    fi
    sudo apt-get install libgtkmm-3.0-dev gnuplot g++ gfortran python libboost-dev cython python-dev python-numpy python-numpy-dev python-setuptools python3 python3-dev python3-setuptools python3-numpy cython3 
    sudo update-alternatives --install /usr/bin/python python /usr/bin/python3 1
    git clone https://github.com/Cantera/cantera.git

branches:
  only:
  - master
env:
  global:
  - CANTERA=/usr/local
  - ASALI_OS='-DASALI_ON_WINDOW=0'
script: |
    if [[ "$TRAVIS_DIST" == "xenial" ]]; then
        cd scons
        python bootstrap.py build/scons
        cd build/scons/
        sudo python setup.py install
        cd ..
        cd ..
        cd ..
        pip3 install ruamel.yaml
    fi
    cd cantera
    scons build system_sundials=n
    sudo scons install
    cd ..
    cd GUI/Ubuntu
    ./compile.sh
